import { useEffect, useMemo, useState } from 'react'
import { differenceInCalendarDays, format, isWithinInterval } from 'date-fns'
import { ArrowLeft, ArrowRight, Bell, BookOpen, Bus, ChevronRight, CircleEllipsis, Eye, EyeOff, Home, Landmark, LoaderCircle, LogOut, Mail, Plus, ReceiptText, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, TrendingUp, Utensils, WalletCards, X } from 'lucide-react'
import type { Session } from '@supabase/supabase-js'
import { Category, Expense, Fund, Profile, WishlistItem, addToFund, createExpense, createWishlistItem, cycleRange, defaultProfile, loadFinanceData, money, supabase, updateProfile, updateWishlistStatus } from './lib'

type Tab = 'home' | 'activity' | 'wishlist' | 'more'
const cats: {name: Category; icon: typeof Utensils}[] = [{name:'Food',icon:Utensils},{name:'Transport',icon:Bus},{name:'Study',icon:BookOpen},{name:'Bills',icon:ReceiptText},{name:'Fun',icon:Sparkles},{name:'Other',icon:CircleEllipsis}]
const catColors: Record<Category,string> = {Food:'#c7e8a3',Transport:'#a8d8e8',Study:'#c9b8ee',Bills:'#f3cb85',Fun:'#f2a9b8',Other:'#c8cbc5'}

export default function App() {
  const [session,setSession]=useState<Session|null>(null), [checking,setChecking]=useState(true)
  useEffect(()=>{
    if(!supabase){setChecking(false);return}
    supabase.auth.getSession().then(({data})=>{setSession(data.session);setChecking(false)})
    const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setChecking(false)})
    return ()=>subscription.unsubscribe()
  },[])
  if(checking)return <LoadingScreen label="Opening your wallet…"/>
  if(!supabase)return <AuthScreen configurationError/>
  if(!session)return <AuthScreen/>
  return <FinanceApp session={session}/>
}

function FinanceApp({session}:{session:Session}) {
  const [tab,setTab]=useState<Tab>('home'), [expenses,setExpenses]=useState<Expense[]>([]), [wishlist,setWishlist]=useState<WishlistItem[]>([]), [funds,setFunds]=useState<Fund[]>([])
  const [profile,setProfile]=useState<Profile>(defaultProfile), [loading,setLoading]=useState(true), [error,setError]=useState('')
  const [showAdd,setShowAdd]=useState(false), [showWish,setShowWish]=useState(false), [showWealth,setShowWealth]=useState(false)
  useEffect(()=>{loadFinanceData(session.user.id).then(data=>{setExpenses(data.expenses);setWishlist(data.wishlist);setFunds(data.funds);setProfile(data.profile)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[session.user.id])
  const range=cycleRange(profile.cycle_start_day)
  const current=useMemo(()=>expenses.filter(e=>isWithinInterval(new Date(e.spent_at),range)),[expenses,range.start.getTime()])
  if(loading)return <LoadingScreen label="Syncing your money…"/>
  const total=current.reduce((s,e)=>s+e.amount,0), budget=profile.monthly_budget||12000, left=budget-total
  const run=async(task:()=>Promise<void>)=>{try{setError('');await task()}catch(e){setError(e instanceof Error?e.message:'Something went wrong')}}
  const addExpense=async(e:Expense)=>run(async()=>{await createExpense(session.user.id,e);setExpenses(items=>[e,...items]);setShowAdd(false)})
  const addWish=async(w:WishlistItem)=>run(async()=>{await createWishlistItem(session.user.id,w);setWishlist(items=>[w,...items]);setShowWish(false)})
  const changeProfile=async(changes:Partial<Profile>)=>run(async()=>{await updateProfile(session.user.id,changes);setProfile(p=>({...p,...changes}))})
  const changeWishStatus=async(id:string,status:WishlistItem['status'])=>run(async()=>{await updateWishlistStatus(id,status);setWishlist(items=>items.map(w=>w.id===id?{...w,status}:w))})
  const contribute=async(kind:Fund['kind'])=>{const fund=funds.find(f=>f.kind===kind);if(!fund)return;const raw=prompt(`How much would you like to add to ${fund.name}?`);const amount=Number(raw);if(!amount||amount<=0)return;await run(async()=>{await addToFund(fund.id,fund.balance,amount);setFunds(items=>items.map(f=>f.id===fund.id?{...f,balance:f.balance+amount}:f));setShowWealth(true)})}
  return <div className="app-shell">
    <header><button className="brand" onClick={()=>setTab('home')}><span>p</span> paisa</button><button className="icon-btn"><Bell size={19}/><i/></button></header>
    {error&&<div className="error-banner">{error}<button onClick={()=>setError('')}>×</button></div>}
    <main>
      {tab==='home'&&<HomePage total={total} left={left} budget={budget} expenses={current} range={range} cycleDay={profile.cycle_start_day} onCycle={d=>changeProfile({cycle_start_day:d})} funds={funds} onFundAdd={contribute} showWealth={showWealth} onToggleWealth={()=>setShowWealth(!showWealth)} onWishlist={()=>setTab('wishlist')}/>} 
      {tab==='activity'&&<ActivityPage expenses={expenses} />}
      {tab==='wishlist'&&<WishlistPage items={wishlist} onAdd={()=>setShowWish(true)} onStatus={changeWishStatus}/>} 
      {tab==='more'&&<MorePage profile={profile} email={session.user.email||''} onChange={changeProfile}/>} 
    </main>
    <nav>{([['home',Home,'Home'],['activity',ReceiptText,'Activity'],['wishlist',ShoppingBag,'Wishlist'],['more',Settings,'More']] as const).map(([id,Icon,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon size={21}/><span>{label}</span></button>)}</nav>
    {tab!=='wishlist'&&<button className="fab" onClick={()=>setShowAdd(true)}><Plus/> Add expense</button>}
    {showAdd&&<ExpenseSheet onClose={()=>setShowAdd(false)} onAdd={addExpense}/>} 
    {showWish&&<WishSheet onClose={()=>setShowWish(false)} onAdd={addWish}/>} 
  </div>
}

function LoadingScreen({label}:{label:string}){return <div className="auth-shell loading-screen"><div className="auth-brand"><span>p</span> paisa</div><LoaderCircle className="spin"/><p>{label}</p></div>}

function AuthScreen({configurationError=false}:{configurationError?:boolean}){const [email,setEmail]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!supabase)return;setBusy(true);setError('');const {error:authError}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setBusy(false);if(authError)setError(authError.message);else setSent(true)};return <div className="auth-shell"><div className="auth-brand"><span>p</span> paisa</div><div className="auth-copy"><p className="eyebrow">YOUR MONEY, YOUR SPACE</p><h1>A calmer way to<br/>track your money.</h1><p>Sign in once. Your expenses stay private and sync wherever you use Paisa.</p></div>{configurationError?<div className="auth-error">Supabase is not configured. Add the project URL and publishable key to <code>.env</code>.</div>:sent?<div className="mail-sent"><Mail/><h2>Check your inbox</h2><p>We sent a secure sign-in link to <b>{email}</b>.</p><button className="text-btn" onClick={()=>setSent(false)}>Use another email</button></div>:<form className="auth-form" onSubmit={submit}><label>Email address<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Mail size={18}/>} Email me a sign-in link</button><small>No password to remember. New emails create an account automatically.</small></form>}</div>}

function HomePage({total,left,budget,expenses,range,cycleDay,onCycle,funds,onFundAdd,showWealth,onToggleWealth,onWishlist}:{total:number;left:number;budget:number;expenses:Expense[];range:{start:Date;end:Date};cycleDay:number;onCycle:(d:number)=>void;funds:Fund[];onFundAdd:(kind:Fund['kind'])=>void;showWealth:boolean;onToggleWealth:()=>void;onWishlist:()=>void}){
 const days=Math.max(1,differenceInCalendarDays(range.end,new Date())+1), daily=Math.max(0,left/days)
 const grouped=cats.map(c=>({...c,value:expenses.filter(e=>e.category===c.name).reduce((s,e)=>s+e.amount,0)})).filter(c=>c.value)
 return <><section className="hello"><p>Good morning</p><h1>Keep it simple,<br/>keep it moving.</h1></section>
 <section className="balance-card"><div className="row"><span>LEFT THIS CYCLE</span><span>{Math.round((Math.max(0,left)/budget)*100)}% left</span></div><strong>{money(left)}</strong><div className="progress"><i style={{width:`${Math.min(100,total/budget*100)}%`}}/></div><div className="row sub"><span>{money(total)} spent</span><span>{money(budget)} budget</span></div><div className="daily"><Sparkles size={17}/><span>You can spend about <b>{money(daily)}</b> per day</span></div></section>
 <section className="cycle"><div><p>YOUR MONEY MONTH</p><h3>{format(range.start,'d MMM')} — {format(range.end,'d MMM')}</h3></div><button onClick={()=>{const d=prompt('What day does your money month start?',String(cycleDay));if(d&&Number(d)>0&&Number(d)<29)onCycle(Number(d))}}>Starts on {cycleDay}th <ChevronRight size={16}/></button></section>
 <section className="section"><div className="section-head"><div><p>SPENDING BREAKDOWN</p><h2>Where it went</h2></div><button>See all</button></div>{grouped.length?<><div className="bar">{grouped.map(g=><i key={g.name} title={g.name} style={{width:`${g.value/total*100}%`,background:catColors[g.name]}}/>)}</div><div className="category-grid">{grouped.map(({name,icon:Icon,value})=><div key={name}><span style={{background:catColors[name]}}><Icon size={17}/></span><div><b>{name}</b><small>{money(value)}</small></div></div>)}</div></>:<div className="empty">Your breakdown will appear after your first expense.</div>}</section>
 <section className="nudge"><div className="nudge-icon"><ShieldCheck/></div><div><p>GENTLE NUDGE</p><h3>Future-you will thank you.</h3><span>Even Rs 100 in your emergency fund is a win.</span><button onClick={()=>onFundAdd('emergency')}>Add to emergency fund <ArrowRight size={16}/></button></div></section>
 <section className="section wealth"><div className="section-head"><div><p>GROWTH POCKETS</p><h2>Your quiet progress</h2></div><button onClick={onToggleWealth}>{showWealth?<EyeOff size={18}/>:<Eye size={18}/>} {showWealth?'Hide':'Reveal'}</button></div>{showWealth?<div className="pockets">{funds.map(f=>{const Icon=f.kind==='emergency'?Landmark:f.kind==='mutual_fund'?TrendingUp:WalletCards;return <button key={f.id} onClick={()=>onFundAdd(f.kind)}><Icon/><span>{f.name}</span><b>{money(f.balance)}</b></button>})}</div>:<div className="hidden-pocket">Hidden for a calmer view. Reveal only when you want to check in.</div>}</section>
 <button className="wish-preview" onClick={onWishlist}><div><p>BEFORE YOU BUY</p><h3>Pause. Think. Then choose.</h3><span>Your wishlist helps you shop with intention.</span></div><ShoppingBag/><ChevronRight/></button></>
}

function ActivityPage({expenses}:{expenses:Expense[]}){const [q,setQ]=useState('');const shown=expenses.filter(e=>(e.note+e.category).toLowerCase().includes(q.toLowerCase()));return <section className="page"><p className="eyebrow">YOUR MONEY</p><h1>Activity</h1><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search expenses"/></div><div className="transactions">{shown.map(e=>{const c=cats.find(c=>c.name===e.category)!;const Icon=c.icon;return <div key={e.id}><span style={{background:catColors[e.category]}}><Icon size={18}/></span><div><b>{e.note||e.category}</b><small>{e.category} · {format(new Date(e.spent_at),'d MMM')}</small></div><strong>- {money(e.amount)}</strong></div>})}</div></section>}

function WishlistPage({items,onAdd,onStatus}:{items:WishlistItem[];onAdd:()=>void;onStatus:(id:string,s:WishlistItem['status'])=>void}){return <section className="page"><p className="eyebrow">BUY WITH INTENTION</p><h1>Wishlist</h1><p className="lead">A quiet place between wanting something and buying it.</p><button className="primary wide" onClick={onAdd}><Plus size={18}/> Add something</button>{items.length===0?<div className="wish-empty"><ShoppingBag/><h2>Your wishlist is empty</h2><p>Next time something catches your eye, keep it here for a little while.</p></div>:<div className="wish-list">{items.map(w=><div key={w.id}><div className="row"><div><small>{w.status==='thinking'?'THINKING ABOUT':'DECIDED'}</small><h3>{w.name}</h3></div><b>{money(w.price)}</b></div><p>{w.answers[0]}</p><div className="choice"><button onClick={()=>onStatus(w.id,'save')} className={w.status==='save'?'chosen':''}>Save the money</button><button onClick={()=>onStatus(w.id,'buy')} className={w.status==='buy'?'chosen':''}>Buy mindfully</button></div></div>)}</div>}</section>}

function MorePage({profile,email,onChange}:{profile:Profile;email:string;onChange:(p:Partial<Profile>)=>void}){return <section className="page"><p className="eyebrow">MAKE IT YOURS</p><h1>Settings</h1><div className="settings-card"><label><div><b>Money month starts</b><small>Use your salary or allowance day</small></div><select value={profile.cycle_start_day} onChange={e=>onChange({cycle_start_day:Number(e.target.value)})}>{Array.from({length:28},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label><div><b>Monthly budget</b><small>Your target for each money month</small></div><button className="setting-value" onClick={()=>{const value=Number(prompt('Monthly budget',String(profile.monthly_budget)));if(value>=0)onChange({monthly_budget:value})}}>{money(profile.monthly_budget)}</button></label><label><div><b>Currency</b><small>Used across your tracker</small></div><span>NPR (Rs)</span></label><label><div><b>Emergency fund reminders</b><small>A gentle reminder each cycle</small></div><input type="checkbox" checked={profile.emergency_reminders} onChange={e=>onChange({emergency_reminders:e.target.checked})}/></label></div><div className="privacy"><ShieldCheck/><div><b>Your numbers are yours.</b><p>Every record is synced to Supabase and protected by your account.</p></div></div><div className="account-card"><div><small>SIGNED IN AS</small><b>{email}</b></div><button onClick={()=>supabase?.auth.signOut()}><LogOut size={17}/> Sign out</button></div></section>}

function ExpenseSheet({onClose,onAdd}:{onClose:()=>void;onAdd:(e:Expense)=>void}){const [amount,setAmount]=useState(''),[category,setCategory]=useState<Category>('Food'),[note,setNote]=useState('');return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="sheet" onSubmit={e=>{e.preventDefault();if(Number(amount)>0)onAdd({id:crypto.randomUUID(),amount:Number(amount),category,note,spent_at:new Date().toISOString()})}}><div className="handle"/><div className="sheet-head"><div><p>QUICK ADD</p><h2>What did you spend?</h2></div><button type="button" className="icon-btn" onClick={onClose}><X/></button></div><label className="amount-input"><span>Rs</span><input autoFocus inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></label><div className="cat-pills">{cats.map(({name,icon:Icon})=><button type="button" className={category===name?'selected':''} onClick={()=>setCategory(name)} key={name}><Icon size={18}/>{name}</button>)}</div><label className="note"><span>What was it? <i>optional</i></span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Lunch, bus, a book…"/></label><button className="primary wide" disabled={!Number(amount)}>Save expense <ArrowRight size={18}/></button></form></div>}

function WishSheet({onClose,onAdd}:{onClose:()=>void;onAdd:(w:WishlistItem)=>void}){const [step,setStep]=useState(0),[name,setName]=useState(''),[price,setPrice]=useState(''),[answers,setAnswers]=useState<string[]>([]);const qs=[`What makes you want this right now?`,`If you wait 7 days, what might change?`,`Would ${money(Number(price)||0)} feel better in savings or a mutual fund?`];return <div className="overlay"><form className="sheet wish-sheet" onSubmit={e=>{e.preventDefault();if(step<3)setStep(step+1);else onAdd({id:crypto.randomUUID(),name,price:Number(price),answers,status:'thinking'})}}><div className="handle"/><div className="sheet-head"><button type="button" className="icon-btn" onClick={step?()=>setStep(step-1):onClose}>{step?<ArrowLeft/>:<X/>}</button><span>{step+1} / 4</span><button type="button" className="text-btn" onClick={onClose}>Close</button></div>{step===0?<><p className="eyebrow">LET IT BREATHE</p><h2>What caught your eye?</h2><label className="note"><span>Item</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Headphones, shoes…"/></label><label className="note"><span>Price</span><input inputMode="decimal" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Rs 0"/></label></>:<><p className="eyebrow">A SMALL PAUSE</p><h2>{qs[step-1]}</h2><textarea autoFocus value={answers[step-1]||''} onChange={e=>{const a=[...answers];a[step-1]=e.target.value;setAnswers(a)}} placeholder="There’s no wrong answer…"/><div className="thought"><Sparkles/><span>{step===3?'Saving it is also a purchase—of more freedom later.':'Honest answers make intentional choices easier.'}</span></div></>}<button className="primary wide" disabled={step===0&&(!name||!Number(price))}>{step===3?'Keep it on my wishlist':'Continue'} <ArrowRight size={18}/></button></form></div>}
